Repository liszkai-dominik/Proj1-Hianyzasok-10A_H, pull requests merged in 2023-02, with the labels that each got.

#32 7. feladat megoldása
  Hianyzasok.py
  Megoldas.py
  Seged.py
  __pycache__/Hianyzasok.cpython-310.pyc
  __pycache__/Megoldas.cpython-310.pyc
  __pycache__/Seged.cpython-310.pyc
  main.py
Labels: task

#34 Magyar matyas/issue33
  Megoldas.py
  __pycache__/Hianyzasok.cpython-310.pyc
  __pycache__/Megoldas.cpython-310.pyc
  __pycache__/Seged.cpython-310.pyc
Labels: bug

#36 Javítás
  Hianyzasok.py
  Megoldas.py
  __pycache__/Hianyzasok.cpython-310.pyc
  __pycache__/Megoldas.cpython-310.pyc
  __pycache__/Seged.cpython-310.pyc
Labels: correcting
