Repository liszkai-dominik/Proj1-Hianyzasok-10A_H, pull requests merged in 2023-03, with the labels that each got.

#39 Megoldás osztály tesztelése
  .vscode/settings.json
  Megoldas.py
  __pycache__/Hianyzasok.cpython-310.pyc
  __pycache__/Megoldas.cpython-310.pyc
  __pycache__/Seged.cpython-310.pyc
  __pycache__/test_Megoldas.cpython-310.pyc
  main.py
  test_Megoldas.py
Labels: testing

#42 Ppt feltöltése
  Projekt.pptx
  __pycache__/Hianyzasok.cpython-310.pyc
  __pycache__/Megoldas.cpython-310.pyc
  __pycache__/Seged.cpython-310.pyc
  __pycache__/test_Megoldas.cpython-310.pyc
  test_Megoldas.py
Labels: task

#48 Javítás 2
  Hianyzasok.py
  Megoldas.py
Labels: correcting

#53 Hétnapja függvény javítása
  Seged.py
Labels: correcting, task
